/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppStoryRouteImport } from './routes/_app/story'
import { Route as AppSavedRouteImport } from './routes/_app/saved'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppGalleryRouteImport } from './routes/_app/gallery'
import { Route as AppContactRouteImport } from './routes/_app/contact'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppListingsIndexRouteImport } from './routes/_app/listings/index'
import { Route as AppCartIndexRouteImport } from './routes/_app/cart/index'
import { Route as AppListingsIdRouteImport } from './routes/_app/listings/$id'
import { Route as AppLegalTermsRouteImport } from './routes/_app/legal/terms'
import { Route as AppLegalPrivacyRouteImport } from './routes/_app/legal/privacy'
import { Route as AppCartSuccessRouteImport } from './routes/_app/cart/success'
import { Route as AppCartCheckoutRouteImport } from './routes/_app/cart/checkout'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStoryRoute = AppStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppGalleryRoute = AppGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppListingsIndexRoute = AppListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => AppRoute,
} as any)
const AppCartIndexRoute = AppCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => AppRoute,
} as any)
const AppListingsIdRoute = AppListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLegalTermsRoute = AppLegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => AppRoute,
} as any)
const AppLegalPrivacyRoute = AppLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppCartSuccessRoute = AppCartSuccessRouteImport.update({
  id: '/cart/success',
  path: '/cart/success',
  getParentRoute: () => AppRoute,
} as any)
const AppCartCheckoutRoute = AppCartCheckoutRouteImport.update({
  id: '/cart/checkout',
  path: '/cart/checkout',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/about': typeof AppAboutRoute
  '/contact': typeof AppContactRoute
  '/gallery': typeof AppGalleryRoute
  '/profile': typeof AppProfileRoute
  '/saved': typeof AppSavedRoute
  '/story': typeof AppStoryRoute
  '/cart/checkout': typeof AppCartCheckoutRoute
  '/cart/success': typeof AppCartSuccessRoute
  '/legal/privacy': typeof AppLegalPrivacyRoute
  '/legal/terms': typeof AppLegalTermsRoute
  '/listings/$id': typeof AppListingsIdRoute
  '/cart/': typeof AppCartIndexRoute
  '/listings/': typeof AppListingsIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AppAboutRoute
  '/contact': typeof AppContactRoute
  '/gallery': typeof AppGalleryRoute
  '/profile': typeof AppProfileRoute
  '/saved': typeof AppSavedRoute
  '/story': typeof AppStoryRoute
  '/': typeof AppIndexRoute
  '/cart/checkout': typeof AppCartCheckoutRoute
  '/cart/success': typeof AppCartSuccessRoute
  '/legal/privacy': typeof AppLegalPrivacyRoute
  '/legal/terms': typeof AppLegalTermsRoute
  '/listings/$id': typeof AppListingsIdRoute
  '/cart': typeof AppCartIndexRoute
  '/listings': typeof AppListingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/gallery': typeof AppGalleryRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/saved': typeof AppSavedRoute
  '/_app/story': typeof AppStoryRoute
  '/_app/': typeof AppIndexRoute
  '/_app/cart/checkout': typeof AppCartCheckoutRoute
  '/_app/cart/success': typeof AppCartSuccessRoute
  '/_app/legal/privacy': typeof AppLegalPrivacyRoute
  '/_app/legal/terms': typeof AppLegalTermsRoute
  '/_app/listings/$id': typeof AppListingsIdRoute
  '/_app/cart/': typeof AppCartIndexRoute
  '/_app/listings/': typeof AppListingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/profile'
    | '/saved'
    | '/story'
    | '/cart/checkout'
    | '/cart/success'
    | '/legal/privacy'
    | '/legal/terms'
    | '/listings/$id'
    | '/cart/'
    | '/listings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contact'
    | '/gallery'
    | '/profile'
    | '/saved'
    | '/story'
    | '/'
    | '/cart/checkout'
    | '/cart/success'
    | '/legal/privacy'
    | '/legal/terms'
    | '/listings/$id'
    | '/cart'
    | '/listings'
  id:
    | '__root__'
    | '/_app'
    | '/_app/about'
    | '/_app/contact'
    | '/_app/gallery'
    | '/_app/profile'
    | '/_app/saved'
    | '/_app/story'
    | '/_app/'
    | '/_app/cart/checkout'
    | '/_app/cart/success'
    | '/_app/legal/privacy'
    | '/_app/legal/terms'
    | '/_app/listings/$id'
    | '/_app/cart/'
    | '/_app/listings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/story': {
      id: '/_app/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof AppStoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gallery': {
      id: '/_app/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AppGalleryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/listings/': {
      id: '/_app/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof AppListingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cart/': {
      id: '/_app/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof AppCartIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/listings/$id': {
      id: '/_app/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof AppListingsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/legal/terms': {
      id: '/_app/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof AppLegalTermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/legal/privacy': {
      id: '/_app/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof AppLegalPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cart/success': {
      id: '/_app/cart/success'
      path: '/cart/success'
      fullPath: '/cart/success'
      preLoaderRoute: typeof AppCartSuccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cart/checkout': {
      id: '/_app/cart/checkout'
      path: '/cart/checkout'
      fullPath: '/cart/checkout'
      preLoaderRoute: typeof AppCartCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppContactRoute: typeof AppContactRoute
  AppGalleryRoute: typeof AppGalleryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSavedRoute: typeof AppSavedRoute
  AppStoryRoute: typeof AppStoryRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCartCheckoutRoute: typeof AppCartCheckoutRoute
  AppCartSuccessRoute: typeof AppCartSuccessRoute
  AppLegalPrivacyRoute: typeof AppLegalPrivacyRoute
  AppLegalTermsRoute: typeof AppLegalTermsRoute
  AppListingsIdRoute: typeof AppListingsIdRoute
  AppCartIndexRoute: typeof AppCartIndexRoute
  AppListingsIndexRoute: typeof AppListingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppContactRoute: AppContactRoute,
  AppGalleryRoute: AppGalleryRoute,
  AppProfileRoute: AppProfileRoute,
  AppSavedRoute: AppSavedRoute,
  AppStoryRoute: AppStoryRoute,
  AppIndexRoute: AppIndexRoute,
  AppCartCheckoutRoute: AppCartCheckoutRoute,
  AppCartSuccessRoute: AppCartSuccessRoute,
  AppLegalPrivacyRoute: AppLegalPrivacyRoute,
  AppLegalTermsRoute: AppLegalTermsRoute,
  AppListingsIdRoute: AppListingsIdRoute,
  AppCartIndexRoute: AppCartIndexRoute,
  AppListingsIndexRoute: AppListingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
